version: 2
updates:
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directories:
      - /apis
      - /client
      - /util
      - /generator
      - /aggregator
      - /webhook
      - /allinone
      - /tests
    schedule:
      interval: weekly
    ignore:
      # k8s.io/apimachinery and k8s.io/api updates always come with k8s.io/client-go updates
      - dependency-name: k8s.io/apimachinery
      - dependency-name: k8s.io/api
